// @ts-check
const cafes = [
 {id:'green',name:'온실 커피',area:'성수',menu:'아메리카노 5,500원',space:'실내 동반',condition:'10kg 이하 · 이동가방 필수',photo:'terrace.jpg',drink:true,garden:false,danger:false,slots:['13:00','14:00','15:00']},
 {id:'slow',name:'느린 오후',area:'성수',menu:'아메리카노 6,000원',space:'마당 동반',condition:'크기 제한 없음 · 실내 동반 불가',photo:'cafe.jpg',drink:false,garden:true,danger:false,slots:['14:00','15:00','16:00']},
 {id:'walk',name:'커피와 산책',area:'연남',menu:'필터커피 6,500원',space:'실내 동반',condition:'10kg 이하 · 이동가방 필수',photo:'coffee.jpg',drink:true,garden:false,danger:false,slots:['11:00','13:00','14:00']},
 {id:'yard',name:'단독 마당',area:'성수',menu:'대관비 매장 확인',space:'맹견 전용 대관',condition:'단독 이용 · 입장조건 사전 확인',photo:'dog.jpg',drink:false,garden:true,danger:true,slots:['12:00','14:00','16:00']}
];
const categories=[{id:'indoor',label:'동반입장',full:'실내 동반입장',icon:'paw-print'},{id:'drink',label:'음료맛집',full:'음료맛집',icon:'coffee'},{id:'danger',label:'맹견전용',full:'맹견 전용 대관',icon:'shield-check'},{id:'garden',label:'넓은마당',full:'넓은 마당',icon:'trees'}];
const state={area:'성수',query:'',filter:'',tab:'home',saved:new Set((localStorage.getItem('r4-saved')??'').split(',').filter(Boolean)),scroll:0};
function appRegion(){const node=document.querySelector('#app');if(!(node instanceof HTMLElement))throw new Error('앱 영역 누락');return node;}
function navigationRegion(){const node=document.querySelector('#navigation');if(!(node instanceof HTMLElement))throw new Error('탐색 영역 누락');return node;}
const app=appRegion();const nav=navigationRegion();
/** @template {keyof HTMLElementTagNameMap} K @param {K} tag @param {string} [className] @param {string} [text] */
function el(tag,className='',text=''){const node=document.createElement(tag);node.className=className;node.textContent=text;return node;}
/** @param {string} name */function icon(name){const image=el('span','icon');image.style.maskImage=`url(assets/${name}.svg)`;image.setAttribute('aria-hidden','true');return image;}
/** @param {string} label @param {()=>void} action @param {string} [className] */
function button(label,action,className=''){const node=el('button',className,label);node.type='button';node.addEventListener('click',action);return node;}
/** @param {string} name @param {string} label @param {()=>void} action */function iconButton(name,label,action){const node=button('',action,'icon-button');node.setAttribute('aria-label',label);node.append(icon(name));return node;}
function reset(){state.filter='';state.query='';state.area='성수';render();app.querySelector('input')?.focus();}
/** @param {string} selected */function filter(selected){state.filter=state.filter===selected?'':selected;render();const control=app?.querySelector(`[data-filter="${selected}"]`);if(control instanceof HTMLElement)control.focus();}
/** @param {typeof cafes[number]} cafe */function matches(cafe){const query=state.query.trim().toLowerCase();return (state.area==='전체'||cafe.area===state.area)&&(!query||`${cafe.name} ${cafe.area}`.toLowerCase().includes(query))&&(!state.filter||(state.filter==='indoor'&&!cafe.garden)||(state.filter==='drink'&&cafe.drink)||(state.filter==='garden'&&cafe.garden)||(state.filter==='danger'&&cafe.danger));}
/** @param {typeof cafes[number]} cafe */function openDetail(cafe){state.scroll=window.scrollY;detail=cafe;returnFocus=document.activeElement instanceof HTMLElement?document.activeElement:null;renderDetail(cafe);window.scrollTo(0,0);}
/** @param {typeof cafes[number]} cafe @param {string} time */function openBooking(cafe,time){const draft=drafts.get(cafe.id)??{date:'12',time:cafe.slots[0],people:'2',pets:'1',confirmed:false};if(time){draft.time=time;draft.date='12';}drafts.set(cafe.id,draft);renderBooking(cafe,draft,'edit');booking.showModal();}
/** @param {typeof cafes[number]} cafe */function card(cafe){const article=el('article');const top=el('div','cafe-top');const photoLink=el('a');photoLink.href=`#${cafe.id}`;photoLink.setAttribute('aria-label',`${cafe.name} 상세 보기`);photoLink.addEventListener('click',event=>{event.preventDefault();openDetail(cafe);});const photo=el('img','cafe-photo');photo.src=`assets/${cafe.photo}`;photo.alt=`${cafe.name} 분위기 예시`;photoLink.append(photo);const info=el('div','cafe-info');const title=el('div','cafe-title');const link=el('a');link.href=`#${cafe.id}`;link.append(el('h3','',cafe.name));link.addEventListener('click',event=>{event.preventDefault();openDetail(cafe);});const save=iconButton('heart',`${cafe.name} 저장`,()=>{if(state.saved.has(cafe.id))state.saved.delete(cafe.id);else state.saved.add(cafe.id);localStorage.setItem('r4-saved',[...state.saved].join(','));save.setAttribute('aria-pressed',String(state.saved.has(cafe.id)));if(state.tab==='saved'){render();const next=app.querySelector('button');next?.focus();}});save.setAttribute('aria-pressed',String(state.saved.has(cafe.id)));title.append(link,save);info.append(title,el('p','muted',`${cafe.area} · ${cafe.menu}`),el('p','',cafe.space),el('p','muted',cafe.condition));top.append(photoLink,info);const slots=el('div','slots');for(const time of cafe.slots){const slot=button(time,()=>openBooking(cafe,time));slot.setAttribute('aria-label',`${cafe.name} 9월 12일 ${time} 예약 선택`);slots.append(slot);}article.append(top,slots);return article;}
function renderResults(){const old=document.querySelector('#results');const section=el('section');section.id='results';const list=cafes.filter(cafe=>state.tab==='saved'?state.saved.has(cafe.id):matches(cafe));if(state.tab==='home'&&state.filter){const summary=el('div','filter-summary');summary.append(el('span','chip',categories.find(item=>item.id===state.filter)?.full??''),button('초기화',reset,'secondary'));section.append(summary);}const title=state.tab==='saved'?'저장한 카페':state.filter||state.query?'조건에 맞는 카페':`${state.area==='전체'?'함께 갈 카페':`${state.area}에서 함께 갈 카페`}`;section.append(el('h2','',title));section.append(el('p','muted list-date',`9월 12일 (토) · ${list.length}곳`));const group=el('ul','cafes');for(const cafe of list){const item=el('li');item.append(card(cafe));group.append(item);}if(!list.length){const empty=el('div','empty');empty.append(el('p','',state.tab==='saved'?'저장한 카페가 없어요':'조건에 맞는 카페가 없어요'),button(state.tab==='saved'?'카페 둘러보기':'조건 초기화',()=>{state.tab='home';reset();},'secondary'));const item=el('li');item.append(empty);group.append(item);}section.append(group);if(old)old.replaceWith(section);else app?.append(section);}
function render(){if(!app||!nav)return;detail=null;nav.hidden=false;app.replaceChildren();const header=el('header','header');header.append(el('h1','',state.tab==='home'?'카페 찾기':state.tab==='saved'?'저장':'예약'));if(state.tab==='home'){const area=el('select','location');area.setAttribute('aria-label','지역 선택');for(const name of ['성수','연남','전체']){const option=el('option','',name);option.value=name;area.append(option);}area.value=state.area;area.addEventListener('change',()=>{state.area=area.value;renderResults();});header.append(area);}app.append(header);if(state.tab==='home'){const search=el('div','search');const input=el('input');input.type='search';input.placeholder='카페 이름 검색';input.setAttribute('aria-label','카페 이름 검색');input.value=state.query;const clear=iconButton('x','검색어 지우기',()=>{state.query='';input.value='';clear.hidden=true;renderResults();input.focus();});clear.hidden=!state.query;input.addEventListener('input',()=>{state.query=input.value;clear.hidden=!state.query;renderResults();});search.append(icon('search'),input,clear);app.append(search);const quick=el('div','quick');quick.setAttribute('aria-label','카페 조건');for(const category of categories){const item=button('',()=>filter(category.id));item.dataset.filter=category.id;item.setAttribute('aria-pressed',String(state.filter===category.id));const slot=el('span','quick-icon');slot.append(icon(category.icon));item.append(slot,el('span','',category.label));quick.append(item);}app.append(quick);if(!state.filter){const section=el('section');section.append(el('h2','','테마로 둘러보기'));const themes=el('div','themes');for(const theme of [{label:'초록빛 실내에서',photo:'terrace.jpg',filter:'indoor'},{label:'산책 뒤, 느긋하게',photo:'dog.jpg',filter:'garden'}]){const item=button('',()=>filter(theme.filter),'theme');const photo=el('img');photo.src=`assets/${theme.photo}`;photo.alt='';item.append(photo,el('span','',theme.label));themes.append(item);}section.append(themes);app.append(section);}}if(state.tab==='bookings'){renderReservations();}else renderResults();nav.replaceChildren();for(const item of [{id:'home',label:'둘러보기',icon:'house'},{id:'saved',label:'저장',icon:'heart'},{id:'bookings',label:'예약',icon:'calendar-days'}]){const target=button('',()=>{positions.set(state.tab,window.scrollY);state.tab=item.id;render();window.scrollTo(0,positions.get(item.id)??0);const active=nav?.querySelector('[aria-current=page]');if(active instanceof HTMLElement)active.focus({preventScroll:true});});if(state.tab===item.id)target.setAttribute('aria-current','page');const mark=el('span','nav-mark');mark.append(icon(item.icon));target.append(mark,el('span','',item.label));nav.append(target);}}
/** @typedef {{date:string,time:string,people:string,pets:string,confirmed:boolean}} Draft */
/** @typedef {{id:string,cafeId:string,date:string,time:string,people:string,pets:string,cancelled:boolean}} Reservation */
/** @type {Map<string,Draft>} */const drafts=new Map();
/** @type {Map<string,number>} */const positions=new Map();
/** @type {typeof cafes[number]|null} */let detail=null;
/** @type {HTMLElement|null} */let returnFocus=null;
function bookingRegion(){const node=document.querySelector('#booking');if(!(node instanceof HTMLDialogElement))throw new Error('예약 화면 누락');return node;}
const booking=bookingRegion();
/** @type {Reservation[]} */const reservations=[];
for(const line of (localStorage.getItem('r4-bookings')??'').split('\n')){const [id,cafeId,date,time,people,pets,cancelled]=line.split('|');if(id&&cafes.some(cafe=>cafe.id===cafeId)&&['12','14','15','16','17','18'].includes(date)&&['1','2','3','4'].includes(people)&&['1','2'].includes(pets))reservations.push({id,cafeId,date,time,people,pets,cancelled:cancelled==='yes'});}
function persistReservations(){localStorage.setItem('r4-bookings',reservations.map(item=>[item.id,item.cafeId,item.date,item.time,item.people,item.pets,item.cancelled?'yes':'no'].join('|')).join('\n'));}
/** @param {string} label @param {()=>void} action */function primary(label,action){const node=button(label,action,'primary');node.append(icon('arrow-right'));return node;}
/** @param {typeof cafes[number]} cafe */function policy(cafe){return cafe.danger?'맹견 전용 시간의 단독 대관이에요. 방문 조건은 매장 확인이 필요해요.':`${cafe.space} · ${cafe.condition}`;}
function backToList(){const cafeId=detail?.id;render();window.scrollTo(0,state.scroll);if(cafeId){const link=app?.querySelector(`a[href="#${cafeId}"]`);if(link instanceof HTMLElement)link.focus({preventScroll:true});}else returnFocus?.focus({preventScroll:true});}
/** @param {typeof cafes[number]} cafe */function renderDetail(cafe){if(!app||!nav)return;nav.hidden=true;app.replaceChildren();const header=el('header','header detail-header');header.append(iconButton('chevron-left','카페 목록으로 돌아가기',backToList),el('h1','',cafe.name));const photo=el('img','detail-photo');if(cafe.danger)photo.classList.add('dog-photo');photo.src=`assets/${cafe.photo}`;photo.alt=`${cafe.name} 분위기 예시 사진`;const introduction=el('section','detail-intro');introduction.append(el('h2','',cafe.name),el('p','muted',`${cafe.area} · ${cafe.menu}`));const conditions=el('section');conditions.append(el('h2','','동반입장 조건'));const description=el('dl','details');const pairs=cafe.danger?[['이용 방식','맹견 전용 단독 대관'],['방문 조건','입장조건 사전 확인'],['대관비','매장 확인 필요']]:[['입장 공간',cafe.space],['크기 조건',cafe.garden?'크기 제한 없음':'10kg 이하'],['준비 사항',cafe.garden?'실내 동반 불가':'이동가방 필수']];for(const [label,value] of pairs)description.append(el('dt','muted',label),el('dd','',value));conditions.append(description);if(cafe.danger)conditions.append(el('p','policy',policy(cafe)));const action=el('section');action.append(primary(cafe.danger?'예약 요청 체험':'예약 일시 선택',()=>openBooking(cafe,'')));app.append(header,photo,introduction,conditions,action);header.querySelector('button')?.focus({preventScroll:true});}
/** @param {string} title */function sheet(title){booking.replaceChildren();booking.scrollTop=0;const header=el('header','header');const heading=el('h2','surface-title',title);heading.id='booking-title';heading.tabIndex=-1;header.append(heading,iconButton('x','예약 화면 닫기',()=>booking.close()));booking.append(header);return heading;}
/** @param {string} label @param {string} value @param {number} max @param {(value:string)=>void} change @param {string} unit */function countSelect(label,value,max,change,unit){const wrapper=el('label','field');wrapper.append(el('span','',label));const select=el('select','select');select.setAttribute('aria-label',label);for(let number=1;number<=max;number++){const option=el('option','',`${number}${unit}`);option.value=String(number);select.append(option);}select.value=value;select.addEventListener('change',()=>change(select.value));wrapper.append(select);return wrapper;}
/** @param {typeof cafes[number]} cafe @param {Draft} draft @param {'edit'|'summary'|'done'} stage */
function renderBooking(cafe,draft,stage){const heading=sheet(stage==='edit'?'예약 일시 선택':stage==='summary'?(cafe.danger?'요청 내용 확인':'예약 내용 확인'):(cafe.danger?'요청 체험을 마쳤어요':'예약 체험을 마쳤어요'));
if(stage==='done'){const content=el('div','sheet-content');content.append(el('p','','실제 예약은 접수되지 않았어요'),el('p','muted',`${cafe.name} · 9월 ${draft.date}일 ${draft.time}`),primary('예약 내역 보기',()=>{booking.close();state.tab='bookings';render();window.scrollTo(0,0);const active=nav.querySelector('[aria-current=page]');if(active instanceof HTMLElement)active.focus({preventScroll:true});}));booking.append(content);heading.focus();return;}
if(stage==='summary'){const content=el('div','sheet-content');const summary=el('dl','details');for(const [label,value] of [['카페',cafe.name],['일시',`2026년 9월 ${draft.date}일 ${draft.time}`],['방문 인원',`${draft.people}명 · 반려동물 ${draft.pets}마리`],['입장 조건',policy(cafe)],['금액 안내',cafe.danger?'대관비는 매장 확인이 필요해요.':`${cafe.menu} (메뉴 가격)`]])summary.append(el('dt','muted',label),el('dd','',value));content.append(summary,el('p','notice','가상 매장과 예시 사진으로 만든 체험이에요. 매장에 전송되지 않고 결제도 진행되지 않아요.'),button('이전',()=>renderBooking(cafe,draft,'edit'),'secondary'),primary(cafe.danger?'요청 체험 완료':'예약 체험 완료',()=>{reservations.unshift({id:String(Date.now()),cafeId:cafe.id,date:draft.date,time:draft.time,people:draft.people,pets:draft.pets,cancelled:false});persistReservations();drafts.delete(cafe.id);renderBooking(cafe,draft,'done');}));booking.append(content);heading.focus();return;}
const content=el('div','sheet-content');content.append(el('p','',cafe.name));const dates=el('fieldset');dates.append(el('legend','','2026년 9월 · 날짜 선택'));const dateGrid=el('div','date-grid');for(const [index,day] of ['12','13','14','15','16','17','18'].entries()){const date=button('',()=>{draft.date=day;for(const control of dateGrid.querySelectorAll('button'))control.setAttribute('aria-pressed',String(control===date));},'choice');date.append(el('span','',`${day}일 (${['토','일','월','화','수','목','금'][index]})`));date.setAttribute('aria-pressed',String(draft.date===day));if(day==='13'){date.disabled=true;date.append(el('span','muted','예약 마감'));}dateGrid.append(date);}dates.append(dateGrid);const times=el('fieldset');times.append(el('legend','','시간 선택'));const timeGrid=el('div','slots');for(const time of cafe.slots){const choice=button(time,()=>{draft.time=time;for(const control of timeGrid.querySelectorAll('button'))control.setAttribute('aria-pressed',String(control===choice));},'choice');choice.setAttribute('aria-pressed',String(draft.time===time));timeGrid.append(choice);}times.append(timeGrid);const counts=el('div','counts');counts.append(countSelect('인원',draft.people,4,value=>{draft.people=value;},'명'),countSelect('반려동물',draft.pets,2,value=>{draft.pets=value;},'마리'));const policyText=el('p','policy',policy(cafe));const agreement=el('label','agreement');const checkbox=el('input');checkbox.type='checkbox';checkbox.checked=draft.confirmed;checkbox.setAttribute('aria-describedby','condition-error');checkbox.addEventListener('change',()=>{draft.confirmed=checkbox.checked;error.hidden=true;checkbox.removeAttribute('aria-invalid');});agreement.append(checkbox,el('span','','동반입장 조건을 확인했어요'));const error=el('p','error','동반입장 조건을 확인해 주세요');error.id='condition-error';error.hidden=true;error.setAttribute('role','alert');const next=primary(cafe.danger?'요청 내용 확인':'예약 내용 확인',()=>{if(!draft.confirmed){error.hidden=false;checkbox.setAttribute('aria-invalid','true');checkbox.focus();return;}renderBooking(cafe,draft,'summary');});content.append(dates,times,counts,policyText,agreement,error,el('p','notice','예약 화면 체험이에요. 매장에 전송되지 않아요.'),next);booking.append(content);if(booking.open)heading.focus();}
function renderReservations(){if(!app)return;const section=el('section');if(!reservations.length){section.className='empty';section.append(el('p','','예약 체험 내역이 없어요'),button('카페 둘러보기',()=>{state.tab='home';reset();},'secondary'));}else{section.append(el('p','notice','이곳의 내역은 체험 기록이에요. 실제 예약은 접수되지 않았어요.'));const list=el('ul','reservations');for(const item of reservations){const cafe=cafes.find(entry=>entry.id===item.cafeId);if(!cafe)continue;const entry=el('li','reservation');entry.append(el('h2','',cafe.name),el('p','',`9월 ${item.date}일 ${item.time}`),el('p','muted',`${item.people}명 · 반려동물 ${item.pets}마리`),el('span','chip',item.cancelled?'취소 체험 완료':cafe.danger?'요청 체험 완료':'예약 체험 완료'));if(!item.cancelled)entry.append(button('예약 취소 체험',()=>{item.cancelled=true;persistReservations();render();const title=app?.querySelector('h1');if(title instanceof HTMLElement){title.tabIndex=-1;title.focus();}},'secondary'));list.append(entry);}section.append(list);}app.append(section);}
render();
