// @ts-check
const cafes = [
 {id:'green',name:'온실 커피',area:'성수',menu:'아메리카노 5,500원',space:'실내 동반',condition:'10kg 이하 · 이동가방 필수',photo:'terrace.jpg',drink:true,garden:false,danger:false,slots:['13:00','14:00','15:00']},
 {id:'slow',name:'느린 오후',area:'성수',menu:'아메리카노 6,000원',space:'마당 동반',condition:'크기 제한 없음 · 실내 동반 불가',photo:'cafe.jpg',drink:false,garden:true,danger:false,slots:['14:00','15:00','16:00']},
 {id:'walk',name:'커피와 산책',area:'연남',menu:'필터커피 6,500원',space:'실내 동반',condition:'10kg 이하 · 이동가방 필수',photo:'coffee.jpg',drink:true,garden:false,danger:false,slots:['11:00','13:00','14:00']},
 {id:'yard',name:'단독 마당',area:'성수',menu:'대관비 매장 확인',space:'맹견 전용 대관',condition:'단독 이용 · 입장조건 사전 확인',photo:'dog.jpg',drink:false,garden:true,danger:true,slots:['12:00','14:00','16:00']}
];
const categories=[{id:'indoor',label:'동반입장',full:'실내 동반입장',icon:'paw-print'},{id:'drink',label:'음료맛집',full:'음료맛집',icon:'coffee'},{id:'danger',label:'맹견전용',full:'맹견 전용 대관',icon:'shield-check'},{id:'garden',label:'넓은마당',full:'넓은 마당',icon:'trees'}];
const state={area:'성수',query:'',filter:'',tab:'home',saved:new Set(),scroll:0};
const app=document.querySelector('#app');const nav=document.querySelector('#navigation');
if(!(app instanceof HTMLElement)||!(nav instanceof HTMLElement))throw new Error('앱 영역을 찾을 수 없어요');
/** @template {keyof HTMLElementTagNameMap} K @param {K} tag @param {string} [className] @param {string} [text] */
function el(tag,className='',text=''){const node=document.createElement(tag);node.className=className;node.textContent=text;return node;}
/** @param {string} name */function icon(name){const image=el('img','icon');image.src=`assets/${name}.svg`;image.alt='';return image;}
/** @param {string} label @param {()=>void} action @param {string} [className] */
function button(label,action,className=''){const node=el('button',className,label);node.type='button';node.addEventListener('click',action);return node;}
/** @param {string} name @param {string} label @param {()=>void} action */function iconButton(name,label,action){const node=button('',action,'icon-button');node.setAttribute('aria-label',label);node.append(icon(name));return node;}
function reset(){state.filter='';state.query='';state.area='성수';render();}
/** @param {string} selected */function filter(selected){state.filter=state.filter===selected?'':selected;render();}
/** @param {typeof cafes[number]} cafe */function matches(cafe){const query=state.query.trim().toLowerCase();return (state.area==='전체'||cafe.area===state.area)&&(!query||`${cafe.name} ${cafe.area}`.toLowerCase().includes(query))&&(!state.filter||(state.filter==='indoor'&&!cafe.garden)||(state.filter==='drink'&&cafe.drink)||(state.filter==='garden'&&cafe.garden)||(state.filter==='danger'&&cafe.danger));}
/** @param {typeof cafes[number]} cafe */function openDetail(cafe){window.alert(`${cafe.name} 상세 화면은 메인 검토 후 연결합니다.`);}
/** @param {typeof cafes[number]} cafe @param {string} time */function openBooking(cafe,time){window.alert(`${cafe.name} ${time} 예약 선택은 메인 검토 후 연결합니다.`);}
/** @param {typeof cafes[number]} cafe */function card(cafe){const article=el('article');const top=el('div','cafe-top');const photoLink=el('a');photoLink.href=`#${cafe.id}`;photoLink.setAttribute('aria-label',`${cafe.name} 상세 보기`);photoLink.addEventListener('click',event=>{event.preventDefault();openDetail(cafe);});const photo=el('img','cafe-photo');photo.src=`assets/${cafe.photo}`;photo.alt=`${cafe.name} 분위기 예시`;photoLink.append(photo);const info=el('div','cafe-info');const title=el('div','cafe-title');const link=el('a');link.href=`#${cafe.id}`;link.append(el('h3','',cafe.name));link.addEventListener('click',event=>{event.preventDefault();openDetail(cafe);});const save=iconButton('heart',`${cafe.name} 저장`,()=>{if(state.saved.has(cafe.id))state.saved.delete(cafe.id);else state.saved.add(cafe.id);save.setAttribute('aria-pressed',String(state.saved.has(cafe.id)));if(state.tab==='saved')render();});save.setAttribute('aria-pressed',String(state.saved.has(cafe.id)));title.append(link,save);info.append(title,el('p','muted',`${cafe.area} · ${cafe.menu}`),el('p','',cafe.space),el('p','muted',cafe.condition));top.append(photoLink,info);const slots=el('div','slots');for(const time of cafe.slots){const slot=button(time,()=>openBooking(cafe,time));slot.setAttribute('aria-label',`${cafe.name} 9월 12일 ${time} 예약 선택`);slots.append(slot);}article.append(top,slots);return article;}
function renderResults(){const old=document.querySelector('#results');const section=el('section');section.id='results';const list=cafes.filter(cafe=>state.tab==='saved'?state.saved.has(cafe.id):matches(cafe));if(state.filter){const summary=el('div','filter-summary');summary.append(el('span','chip',categories.find(item=>item.id===state.filter)?.full??''),button('초기화',reset,'secondary'));section.append(summary);}const title=state.tab==='saved'?'저장한 카페':state.filter||state.query?'조건에 맞는 카페':`${state.area==='전체'?'함께 갈 카페':`${state.area}에서 함께 갈 카페`}`;section.append(el('h2','',title));section.append(el('p','muted list-date',`9월 12일 (토) · ${list.length}곳`));const group=el('div','cafes');for(const cafe of list)group.append(card(cafe));if(!list.length){const empty=el('div','empty');empty.append(el('p','',state.tab==='saved'?'저장한 카페가 없어요':'조건에 맞는 카페가 없어요'),button(state.tab==='saved'?'카페 둘러보기':'조건 초기화',()=>{state.tab='home';reset();},'secondary'));group.append(empty);}section.append(group);if(old)old.replaceWith(section);else app?.append(section);}
function render(){if(!app||!nav)return;app.replaceChildren();const header=el('header','header');header.append(el('h1','',state.tab==='home'?'카페 찾기':state.tab==='saved'?'저장':'예약'));if(state.tab==='home'){const area=el('select','location');area.setAttribute('aria-label','지역 선택');for(const name of ['성수','연남','전체']){const option=el('option','',name);option.value=name;area.append(option);}area.value=state.area;area.addEventListener('change',()=>{state.area=area.value;renderResults();});header.append(area);}app.append(header);if(state.tab==='home'){const search=el('div','search');const input=el('input');input.type='search';input.placeholder='지역, 카페 이름 검색';input.setAttribute('aria-label','지역, 카페 이름 검색');input.value=state.query;const clear=iconButton('x','검색어 지우기',()=>{state.query='';input.value='';clear.hidden=true;renderResults();input.focus();});clear.hidden=!state.query;input.addEventListener('input',()=>{state.query=input.value;clear.hidden=!state.query;renderResults();});search.append(icon('search'),input,clear);app.append(search);const quick=el('div','quick');quick.setAttribute('aria-label','카페 조건');for(const category of categories){const item=button('',()=>filter(category.id));item.setAttribute('aria-pressed',String(state.filter===category.id));const slot=el('span','quick-icon');slot.append(icon(category.icon));item.append(slot,el('span','',category.label));quick.append(item);}app.append(quick);if(!state.filter){const section=el('section');section.append(el('h2','','테마로 둘러보기'));const themes=el('div','themes');for(const theme of [{label:'초록빛 실내에서',photo:'terrace.jpg',filter:'indoor'},{label:'산책 뒤, 느긋하게',photo:'dog.jpg',filter:'garden'}]){const item=button('',()=>filter(theme.filter),'theme');const photo=el('img');photo.src=`assets/${theme.photo}`;photo.alt='';item.append(photo,el('span','',theme.label));themes.append(item);}section.append(themes);app.append(section);}}if(state.tab==='bookings'){const empty=el('div','empty');empty.append(el('p','','예약 체험 내역이 없어요'),button('카페 둘러보기',()=>{state.tab='home';render();},'secondary'));app.append(empty);}else renderResults();nav.replaceChildren();for(const item of [{id:'home',label:'둘러보기',icon:'house'},{id:'saved',label:'저장',icon:'heart'},{id:'bookings',label:'예약',icon:'calendar-days'}]){const target=button('',()=>{state.tab=item.id;render();window.scrollTo(0,0);});if(state.tab===item.id)target.setAttribute('aria-current','page');const mark=el('span','nav-mark');mark.append(icon(item.icon));target.append(mark,el('span','',item.label));nav.append(target);}}
render();
