"""Build a classic-script entry for direct file:// previews (no runtime imports)."""
from pathlib import Path
root = Path(__file__).resolve().parent / 'dist'
parts = []
for filename in ('data.js', 'icons.js', 'app.js'):
    text = (root / filename).read_text()
    lines = [line for line in text.splitlines() if not line.startswith('import ')]
    parts.append('\n'.join(lines).replace('export const ', 'const ').replace('export function ', 'function '))
(root / 'app.bundle.js').write_text('// Generated by ../build.py; edit the source modules.\n(() => {\n' + '\n'.join(parts) + '\n})();\n')
