const {chromium,expect}=require('../../../../todo/node_modules/@playwright/test');
const fs=require('node:fs');const path=require('node:path');
(async()=>{const browser=await chromium.launch({channel:'chrome'});const rows=[];
for(const width of [320,390]){const page=await browser.newPage({viewport:{width,height:740}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const protocol of ['file','http']){await page.goto(protocol==='file'?`file://${path.resolve(__dirname,'../dist/index.html')}`:'http://127.0.0.1:4198');await expect(page.getByRole('heading',{name:'오늘 뭐 먹지?'})).toBeVisible();await page.getByRole('button',{name:'내 냉장고',exact:true}).click();await expect(page.getByRole('button',{name:'재료 추가',exact:true})).toBeVisible();rows.push({width,protocol,entry:true});}
const box=page.getByRole('checkbox',{name:'토마토 선택',exact:true});await box.focus();await page.keyboard.press('Space');await expect(box).toBeFocused();expect(await box.evaluate(e=>getComputedStyle(e).cursor)).toBe('pointer');await box.focus();await page.keyboard.press('Space');await expect(box).toBeFocused();
const filter=page.getByRole('button',{name:'채소',exact:true});await filter.focus();await page.keyboard.press('Enter');await expect(filter).toBeFocused();
const metric=await page.evaluate(()=>({fonts:[...new Set([...document.querySelectorAll('h1,h2,p,button,small,.count-tag,.selection span')].filter(e=>e.getClientRects().length).map(e=>getComputedStyle(e).fontSize))],left:getComputedStyle(document.querySelector('main')).paddingLeft,right:getComputedStyle(document.querySelector('main')).paddingRight,plusName:document.querySelector('[data-action=manual]').getAttribute('aria-label'),plusText:document.querySelector('[data-action=manual]').textContent.trim()}));expect(metric.fonts.length).toBeLessThanOrEqual(3);expect(metric.plusText).toBe('');await page.screenshot({path:`${__dirname}/final-pantry-${width}.png`});
await page.getByRole('button',{name:'사진으로 재료 등록'}).click();await page.evaluate(()=>{window.cameraCalls=0;window.cameraStops=0;navigator.mediaDevices.getUserMedia=()=>{window.cameraCalls++;return new Promise(resolve=>window.cameraResolve=resolve)};});await page.getByRole('button',{name:'카메라 켜기'}).click();await expect(page.getByRole('button',{name:'카메라 연결 중'})).toBeDisabled();await page.screenshot({path:`${__dirname}/final-pending-${width}.png`});await page.getByRole('button',{name:'등록 취소'}).click();await page.evaluate(()=>window.cameraResolve({getTracks:()=>[{stop:()=>window.cameraStops++}]}));expect(await page.evaluate(()=>window.cameraCalls)).toBe(1);await expect.poll(()=>page.evaluate(()=>window.cameraStops)).toBe(1);
await page.getByRole('button',{name:'사진으로 재료 등록'}).click();await page.locator('#upload').setInputFiles({name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('invalid')});await expect(page.getByRole('alert')).toContainText('이미지 파일');await page.locator('#upload').setInputFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('invalid')});await expect(page.getByRole('alert')).toContainText('사진을 읽을 수 없어요');await page.screenshot({path:`${__dirname}/final-invalid-${width}.png`});
await page.getByRole('button',{name:'직접 재료 선택'}).click();const input=page.getByRole('searchbox',{name:'재료 찾기'});const before=await input.boundingBox();await input.focus();const after=await input.boundingBox();expect(before).toEqual(after);await page.emulateMedia({forcedColors:'active'});expect(await input.evaluate(e=>getComputedStyle(e).outlineStyle)).toBe('solid');await page.screenshot({path:`${__dirname}/final-focus-${width}.png`});await page.emulateMedia({forcedColors:'none'});
await page.getByRole('button',{name:'등록 취소'}).click();const button=page.locator('.primary');const rect=await button.boundingBox();const normal=await button.evaluate(e=>getComputedStyle(e).backgroundColor);await button.hover();await page.waitForTimeout(190);const hover=await button.evaluate(e=>({bg:getComputedStyle(e).backgroundColor,transform:getComputedStyle(e).transform,shadow:getComputedStyle(e).boxShadow,duration:getComputedStyle(e).transitionDuration}));expect(hover.bg).not.toBe(normal);expect(hover.transform).toBe('none');expect(await button.boundingBox()).toEqual(rect);await page.mouse.move(0,0);await page.waitForTimeout(190);expect(await button.evaluate(e=>getComputedStyle(e).backgroundColor)).toBe(normal);expect(errors).toEqual([]);rows.push({width,keyboardFocus:true,metric,pendingCancelledTrackStopped:true,invalidFilesRecover:true,focusStable:true,hoverEnterExit:hover,errors});await page.close();}
await browser.close();fs.writeFileSync(`${__dirname}/final-results.json`,JSON.stringify(rows,null,2));console.log('final review regressions PASS')})().catch(e=>{console.error(e);process.exitCode=1});
